feat: Добавил функционал ленты пользователя.
gringrowin/java-filmorate pull request #11
Opened 2023-04-30 19:37 UTC by KlingTone

Новое:

FeedDbStorage;
Новая SQL таблица Feed;
Добавлены новые запросы в UserService методы добавления/удаления лайков/друзей;
Немного изменил ErrorHandle. При ошибки сервера теперь выводится сообщение ошибки;
Позволил себе залезть в properties и добавил туда несколько новый строк. Данные строки увидел в Пачке от Николая Верховцева. Суть эти строчек в том, что появляется новый эндпоинт h2 (localhost:8080/h2), перейдя по которому можно увидеть графическое представление БД с возможностью отправлять запросы. Для меня это удобно, т.к. у меня нет Ultimate Edition Idea;
Директория enums с двумя новыми enum;
Примечание для Андрея:
Когда закончишь делать отзывы, нужно будет кому-то добавить несколько запросов в твои методы. Так любая работа пользователя с отзывами будет фиксироваться в ленте. Сообщи, пожалуйста, когда сделаешь. Тебе или мне нужно будет добавить.

Комментируйте, если что-то не понравится в коде - исправлю.

2023-05-06 06:12 UTC, gringrowin requested changes
Пока предварительно, будет понятней когда сольешь develop.

2023-05-06 06:12 UTC, gringrowin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikeDbStorage.java
> +        sql = "INSERT INTO Feed " +
Возможно все таки вынести это в FeedService и FeedStorage и обращаться к нему из сервисного слоя, только, нужно получается фиксировать прошла ли успешно транзакция в БД.

2023-05-06 06:12 UTC, gringrowin commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private long timestamp;
Рассматривал возможность сразу использовать тип Instant?

2023-05-06 06:12 UTC, gringrowin commented on src/main/resources/schema.sql
> +    event_timestamp bigint,
и может здесь использовать тип Timestamp?

2023-05-06 06:12 UTC, gringrowin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikeDbStorage.java
> +        sql = "INSERT INTO Feed " +
аналогично комментарию выше!

2023-05-07 13:37 UTC, KlingTone commented
Вынес запрос добавления в ленту в FeedService. С Instant и Timestamp возникли проблемы при тестировании в постмане. Там нужно все в миллисекундах только.

2023-05-07 14:05 UTC, MironovNikita reviewed
Написал пару своих комментариев и есть 1 момент, который я бы поправил. В остальном всё отлично!

2023-05-07 14:05 UTC, MironovNikita commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +
Здесь используешь аннотацию @Slf4j, но не делаешь логирование.

2023-05-07 14:26 UTC, MironovNikita approved these changes

2023-05-07 16:01 UTC, Andrey-VU approved these changes
В целом, всё ок! Очень понравилось читать первый развёрнутый комментарий, о том, что сделано, и какие-то отдельные примечания, адресованные конкретным разработчикам)

2023-05-07 16:01 UTC, Andrey-VU commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> -        getReviewById(review.getReviewId());
Поскольку я не понимаю, где происходит проверка наличия сущности и проброса исключения, если сущности нет в БД, предлагаю вернуть эту строчку кода.

2023-05-07 16:01 UTC, Andrey-VU commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> -        getReviewById(id);
Поскольку я не понимаю, где происходит проверка наличия сущности и проброса исключения, если сущности нет в БД, предлагаю вернуть эту строчку кода.

2023-05-07 16:25 UTC, merged