Sprint 9 Controllers films users
gringrowin/java-filmorate pull request #3
Opened 2023-03-12 20:08 UTC by gringrowin

2023-03-13 13:47 UTC, YazykovMikhail requested changes

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Так же логируй не только что пришло в запросе, но и какой ответ был отправлен контроллером
Касается всех

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(max = 200, message = "Description length must be not more 200 characters")
@Size(min = 1, max = 200, message = "Description length must be not more 200 characters")

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer rate;
Вроде в задание нет этого поля

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/validation/validators/FilmReleaseDateValidator.java
> +                && releaseDateField.isAfter(LocalDate.of(1895, 12, 28));
Вообще конечно, эта аннотация будет работать только для этого кода и этого конкретного случае. Но дальше появится еще один контроллер и там тоже нужно удет ограничить дату6 придетс писать новую аннотацию? 
Если есть желание, напиши аннотацию которая пониманиет аргументы, в каком промежуткке долдна быть дата) 
Вот то и правда будет полезно. Но это не обязательно

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmRepository.java
> +        if(films.containsValue(film)) {
поставь на первое место в методе валидаццию, это более логично

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserRepository.java
> +                setNameAndId(user);
не лучший метод. Каждый метод долден отвечать за что то свое. 
Плюс в методе update опловина метода setNameAndId не нужно, потому что id должен приходить в запросе. А если id н пришел, получается ты его вставишь. хотя должна быть ошибка. 
И только на следующем шаге ты это проверишь. 
Ращдели методы. 
В update вообще не нужно сетать id
А в методе create можно просто и без отдельного метода:
user.setId(getIdGenerator);

2023-03-13 13:47 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserRepository.java
> +                if (!users.containsKey(user.getId())) {
И как раз после изменения выше, валидацию вынесешь в начала метода

2023-03-15 20:33 UTC, gringrowin commented on src/main/java/ru/yandex/practicum/filmorate/validation/validators/FilmReleaseDateValidator.java
> +                && releaseDateField.isAfter(LocalDate.of(1895, 12, 28));
Пока не успеваю с этим разобраться...

2023-03-16 13:02 UTC, YazykovMikhail approved these changes
Немного прорустил, но это все равно тема будущей лекции, так что поправишь в новом здании

2023-03-16 13:02 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmRepository.add(film);
тебе filmRepository должен вернуть новый Film c установленым id и именно его ты логируешь в ответ и возвраешь

2023-03-16 13:02 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmRepository.java
> +    public void add(Film film) {
немного пропустил, add должен возвращать Film

2023-03-16 13:02 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmRepository.java
> +    public void update(Film film) {
немного пропустил, update должен возвращать Film

2023-03-16 13:02 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserRepository.java
> +        public void add(User user) {
метод долже возвращать User

2023-03-16 13:02 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserRepository.java
> +        public void update(User user) {
метод долже возвращать User

2023-03-18 14:57 UTC, merged